#version: "3.9"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - homie-demo
    ports:
      - "8080:8080"

  database:
    image: 'postgres:14.1-alpine'
    environment:
      POSTGRES_USER: homie-demo-db
      POSTGRES_PASSWORD: "Postgr@s321!"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  homie-demo:
    image: "ghcr.io/digissance/homie-demo:${TAG}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/homie-demo-db
      SPRING_DATASOURCE_USERNAME: homie-demo-db
      SPRING_DATASOURCE_PASSWORD: "Postgr@s321!"
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      database:
        condition: service_healthy
