version: "3.9"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - www.backend.com
    ports:
      - "8080:8080"

  database:
    image: 'postgres:13.1-alpine'
    environment:
      POSTGRES_USER: homie-demo-db
      POSTGRES_PASSWORD: "Postgr@s321!"
    ports:
      - "5432:5432"
  www.backend.com:
    image: "ghcr.io/digissance/homie-demo:${TAG}"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/homie-demo-db
      SPRING_DATASOURCE_USERNAME: homie-demo-db
      SPRING_DATASOURCE_PASSWORD: "Postgr@s321!"
      SPRING_PROFILES_ACTIVE: dev
#      GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_OAUTH_CLIENT_ID}
#      GOOGLE_OAUTH_CLIENT_SECRET: ${GOOGLE_OAUTH_CLIENT_SECRET}
      SECURITY_DEBUG_ENABLED: "true"
#    ports:
#      - "8080:8080"
    depends_on:
      - database
