logging:
  level:
    web:
      DEBUG
    org:
      hibernate.orm.jdbc.bind: TRACE
      springframework:
        security: TRACE
spring:
  sql:
    init:
      mode: always
  datasource:
    generate-unique-name: false
    name: homie-demo-db
    url: "${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE}"
    username: "${SPRING_DATASOURCE_USERNAME:SA}"
    password: "${SPRING_DATASOURCE_PASSWORD:SA}"
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:2}
  application:
    name: homie-demo
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true
app:
  security:
    cookie:
      secured: false
    jwt:
      token_age: 5
      key: 9faa372517ac1d389758d3750fc07acf00f542277f26fec1ce4593e93f64e443
    debug:
      enabled: true