spring:
  sql:
    init:
      mode: always
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:2}
  application:
    name: homie-demo
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
      probes:
        enabled: true

app:
  security:
    cookie:
      secured: true
    jwt:
      token_age: 60
      key: "${APP_JWT_KEY:123456}"
    debug:
      enabled: false